services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: google-serp-exporter

    ports:
      - "8000:8000"

    volumes:
      - .:/var/www/html
      - app-temp:/var/www/html/temp
      - app-log:/var/www/html/log
      - app-storage:/var/www/html/storage

    environment:
      # API klíč pro SerpApi
      SERPAPI_API_KEY: "${SERPAPI_API_KEY}"

      # Umístění SQLite databáze
      DB_PATH: "/var/www/html/storage/database.sqlite"

volumes:
  app-temp:
  app-log:
  app-storage: